.TH "CBOR2JSON" "1" "April 2016" "" ""
.SH "NAME"
\fBcbor2json\fR \- convert CBOR wire protocol to JSON
.SH SYNOPSIS
.P
.RS 2
.nf
cbor2json test\.cbor > test\.json
.fi
.RE
.SH DESCRIPTION
.P
\fBcbor2json\fP creates a JSON file that mirrors (somewhat) the intent of the input
set of CBOR files\.  For the subset of CBOR that directly maps to JSON, the
output will seem reasonable\.  For CBOR inputs that do not map nicely to JSON,
substitutions are made that may or may not match your expectations\.  For
example, the input:
.P
.RS 2
.nf
0xc100
  c1                \-\- Tag 1 (Date)
    00              \-\- 0
.fi
.RE
.P
produces the following output that does not round\-trip back to the same CBOR
input:
.P
.RS 2
.nf
"1970\-01\-01T00:00:00\.000Z"
.fi
.RE
.SH OPTIONS
.P
\fB\-\fP: read from stdin instead of a file\.  This is the default\.
.P
\fB\-x [string]\fP: read the input from the hex\-encoded string on the command line
.P
\fB\-V, \-\-version\fP: print the node\-cbor version and exit
.P
\fB\-h, \-\-help\fP: print some help text and exit
.SH SEE ALSO
.RS 0
.IP \(bu 2
node\-cbor \fIhttps://github\.com/hildjj/node\-cbor\fR
.IP \(bu 2
RFC 7049 \fIhttp://tools\.ietf\.org/html/rfc7049\fR

.RE
