.TH "CBOR2COMMENT" "1" "April 2016" "" ""
.SH "NAME"
\fBcbor2comment\fR \- convert CBOR wire protocol to commented version
.SH SYNOPSIS
.P
.RS 2
.nf
cbor2comment test\.cbor > test\.txt
.fi
.RE
.SH DESCRIPTION
.P
\fBcbor2comment\fP creates a commented version of an input bytestream\.  For
example, if the input contained the two bytes (in hex) \fB61 61\fP, the output
would be:
.P
.RS 2
.nf
  61                \-\- String, length: 1
    61              \-\- "a"
0x6161
.fi
.RE
.SH OPTIONS
.P
\fB\-\fP: read from stdin instead of a file\.  This is the default\.
.P
\fB\-t NUM, \-\-tabsize NUM\fP: the number of 2\-space tab indents to move the '\-\-' to the right\.
Eventually, this will be replaced with an algorithm that takes two passes
over the input\.
.P
\fB\-x [string]\fP: read the input from the hex\-encoded string on the command line
.P
\fB\-V, \-\-version\fP: print the node\-cbor version and exit
.P
\fB\-h, \-\-help\fP: print some help text and exit
.SH TODO
.RS 0
.IP \(bu 2
\fBcbor2comment\fP is not built for execution speed or reuse\.
.IP \(bu 2
Make 2 passes over the input\.
.IP \(bu 2
Move the summary hex output to the beginning\.

.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
node\-cbor \fIhttps://github\.com/hildjj/node\-cbor\fR
.IP \(bu 2
RFC 7049 \fIhttp://tools\.ietf\.org/html/rfc7049\fR

.RE
