.TH "CBOR2DIAG" "1" "April 2016" "" ""
.SH "NAME"
\fBcbor2diag\fR \- convert CBOR wire protocol to diagnostic text
.SH SYNOPSIS
.P
.RS 2
.nf
cbor2diag test\.cbor > test\.txt
.fi
.RE
.SH DESCRIPTION
.P
\fBcbor2diag\fP outputs the diagnostic format from RFC 7049 that corresponds to the
CBOR files that were input\.  For example, the following input:
.P
.RS 2
.nf
0xc100
  c1                \-\- Tag 1 (Date)
    00              \-\- 0
.fi
.RE
.P
produces:
.P
.RS 2
.nf
1(0)
.fi
.RE
.SH OPTIONS
.P
\fB\-\fP: read from stdin instead of a file\.  This is the default\.
.P
\fB\-x [string]\fP: read the input from the hex\-encoded string on the command line
.P
\fB\-V, \-\-version\fP: print the node\-cbor version and exit
.P
\fB\-h, \-\-help\fP: print some help text and exit
.SH SEE ALSO
.RS 0
.IP \(bu 2
node\-cbor \fIhttps://github\.com/hildjj/node\-cbor\fR
.IP \(bu 2
RFC 7049 \fIhttp://tools\.ietf\.org/html/rfc7049\fR

.RE
