#!/usr/bin/env sh

rm -rf lib-cov covershot
jscoverage --no-highlight lib lib-cov
./node_modules/node-jsmeter/bin/jsmeter.js -o ./covershot/jsmeter/ ./lib/
./node_modules/.bin/nodeunit test
./node_modules/covershot/bin/covershot covershot/data -f html