// Generated by CoffeeScript 1.10.0
(function() {
  var error;

  try {
    require('source-map-support').install();
  } catch (error) {
    // istanbul ignore next;
    void 0;
  }

  exports.Commented = require('./commented');

  exports.Diagnose = require('./diagnose');

  exports.Decoder = require('./decoder');

  exports.Encoder = require('./encoder');

  exports.Simple = require('./simple');

  exports.Tagged = require('./tagged');

  exports.BinaryParser = require('../vendor/binary-parse-stream');

  exports.comment = exports.Commented.comment;

  exports.decodeAll = exports.Decoder.decodeAll;

  exports.decodeFirst = exports.Decoder.decodeFirst;

  exports.diagnose = exports.Diagnose.diagnose;

  exports.encode = exports.Encoder.encode;

}).call(this);

//# sourceMappingURL=cbor.js.map
