// Generated by CoffeeScript 1.7.1
(function() {
  var MT, NUM_BYTES, SIMPLE, TAG;

  MT = (function() {
    function MT() {}

    MT.POS_INT = 0;

    MT.NEG_INT = 1;

    MT.BYTE_STRING = 2;

    MT.UTF8_STRING = 3;

    MT.ARRAY = 4;

    MT.MAP = 5;

    MT.TAG = 6;

    MT.SIMPLE_FLOAT = 7;

    return MT;

  })();

  exports.MT = MT;

  TAG = (function() {
    function TAG() {}

    TAG.DATE_STRING = 0;

    TAG.DATE_EPOCH = 1;

    TAG.POS_BIGINT = 2;

    TAG.NEG_BIGINT = 3;

    TAG.DECIMAL_FRAC = 4;

    TAG.BIGFLOAT = 5;

    TAG.BASE64URL_EXPECTED = 21;

    TAG.BASE64_EXPECTED = 22;

    TAG.BASE16_EXPECTED = 23;

    TAG.CBOR = 24;

    TAG.URI = 32;

    TAG.BASE64URL = 33;

    TAG.BASE64 = 34;

    TAG.REGEXP = 35;

    TAG.MIME = 36;

    return TAG;

  })();

  exports.TAG = TAG;

  NUM_BYTES = (function() {
    function NUM_BYTES() {}

    NUM_BYTES.ZERO = 0;

    NUM_BYTES.ONE = 24;

    NUM_BYTES.TWO = 25;

    NUM_BYTES.FOUR = 26;

    NUM_BYTES.EIGHT = 27;

    return NUM_BYTES;

  })();

  exports.NUM_BYTES = NUM_BYTES;

  SIMPLE = (function() {
    function SIMPLE() {}

    SIMPLE.FALSE = 20;

    SIMPLE.TRUE = 21;

    SIMPLE.NULL = 22;

    SIMPLE.UNDEFINED = 23;

    return SIMPLE;

  })();

  exports.SIMPLE = SIMPLE;

}).call(this);
