// Generated by CoffeeScript 1.10.0
(function() {
  this.MT = (function() {
    function MT() {}

    MT.POS_INT = 0;

    MT.NEG_INT = 1;

    MT.BYTE_STRING = 2;

    MT.UTF8_STRING = 3;

    MT.ARRAY = 4;

    MT.MAP = 5;

    MT.TAG = 6;

    MT.SIMPLE_FLOAT = 7;

    return MT;

  })();

  this.TAG = (function() {
    function TAG() {}

    TAG.DATE_STRING = 0;

    TAG.DATE_EPOCH = 1;

    TAG.POS_BIGINT = 2;

    TAG.NEG_BIGINT = 3;

    TAG.DECIMAL_FRAC = 4;

    TAG.BIGFLOAT = 5;

    TAG.BASE64URL_EXPECTED = 21;

    TAG.BASE64_EXPECTED = 22;

    TAG.BASE16_EXPECTED = 23;

    TAG.CBOR = 24;

    TAG.URI = 32;

    TAG.BASE64URL = 33;

    TAG.BASE64 = 34;

    TAG.REGEXP = 35;

    TAG.MIME = 36;

    return TAG;

  })();

  this.NUMBYTES = (function() {
    function NUMBYTES() {}

    NUMBYTES.ZERO = 0;

    NUMBYTES.ONE = 24;

    NUMBYTES.TWO = 25;

    NUMBYTES.FOUR = 26;

    NUMBYTES.EIGHT = 27;

    NUMBYTES.INDEFINITE = 31;

    return NUMBYTES;

  })();

  this.SIMPLE = (function() {
    function SIMPLE() {}

    SIMPLE.FALSE = 20;

    SIMPLE.TRUE = 21;

    SIMPLE.NULL = 22;

    SIMPLE.UNDEFINED = 23;

    return SIMPLE;

  })();

  this.SYMS = (function() {
    function SYMS() {}

    SYMS.NULL = Symbol('null');

    SYMS.UNDEFINED = Symbol('undef');

    SYMS.PARENT = Symbol('parent');

    SYMS.BREAK = Symbol('break');

    SYMS.STREAM = Symbol('stream');

    return SYMS;

  })();

}).call(this);

//# sourceMappingURL=constants.js.map
