// Generated by CoffeeScript 1.7.1
(function() {
  var Tagged;

  Tagged = (function() {
    function Tagged(tag, value, err) {
      this.tag = tag;
      this.value = value;
      this.err = err;
      if (typeof this.tag !== 'number') {
        throw new Error("Invalid tag type (" + (typeof this.tag) + ")");
      }
      if ((this.tag < 0) || ((this.tag | 0) !== this.tag)) {
        throw new Error("Tag must be a positive integer: " + this.tag);
      }
    }

    Tagged.prototype.toString = function() {
      return "" + this.tag + "(" + (JSON.stringify(this.value)) + ")";
    };

    Tagged.prototype.generateCBOR = function(gen) {
      gen._packTag(this.tag);
      return gen._pack(this.value);
    };

    return Tagged;

  })();

  module.exports = Tagged;

}).call(this);
