name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm i -r
      - run: npm run build
      - run: npm run docs || true
      - run: npm run copy
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
      - run: npx monopub delete devDependencies,scripts
      - run: npx monopub exec 'npm publish --access public --provenance'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
